### ISSUE TITLE
Class 'Rappasoft\LaravelLivewireTables\DataTableComponent' not found

### ISSUE THREAD

**Issue by maarufadam** [rappasoft/laravel-livewire-tables-demo#4]
I am using PHP 7.3, Laravel 8.83.3,

When I setup this package in my project, I gives me this error.

 Error 

  Class 'Rappasoft\LaravelLivewireTables\DataTableComponent' not found

  at app/Http/Livewire/AccreditedFaqsTable.php:12
      8▕ use Illuminate\Database\Eloquent\Builder;
      9▕ use Rappasoft\LaravelLivewireTables\DataTableComponent;
     10▕ use Rappasoft\LaravelLivewireTables\Views\Column;
     11▕ 
  ➜  12▕ class AccreditedFaqsTable extends DataTableComponent
     13▕ {
     14▕     public bool $columnSelect = true;
     15▕     public string $defaultSortColumn = 'sort';
     16▕     public bool $reorderEnabled = true;

      +2 vendor frames 
  3   [internal]:0
      Composer\Autoload\ClassLoader::loadClass()

  4   [internal]:0
      spl_autoload_call()

**Comment by rappasoft** [comment]
If this is still an issue please post it on the actual package repository.
